version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env.sh
# TO RUN THE LOCAL DATABASE, PLEASE UNCOMMENT THE FOLLOWING LINES:

    # environment:
    #   - PORT=8000
    #   - PGURL=postgres://postgres:postgres@db:5432/agendinha
    #   - SECRET_KEY= "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
  #   depends_on:
  #     - db
  # db:
  #   image: postgres
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=agendinha